In [ ]:
import numpy as np
# images:入力画像データ
# flt_h:フィルタの高さ
# flt_w:フィルタの幅
# out_h:出力データの高さ
# out_w:出力データの幅
# stride:ストライド
# pad:パディング
def im2col(images, flt_h, flt_w, out_h, out_w, stride, pad):
   
    n_bt, n_ch, img_h, img_w = images.shape
    
    img_pad = np.pad(images, [(0,0), (0,0), (pad, pad), (pad, pad)], "constant")
    cols = np.zeros((n_bt, n_ch, flt_h, flt_w, out_h, out_w))

    for h in range(flt_h):
        h_lim = h + stride*out_h
        for w in range(flt_w):
            w_lim = w + stride*out_w
            cols[:, :, h, w, :, :] = img_pad[:, :, h:h_lim:stride, w:w_lim:stride]

    cols = cols.transpose(1, 2, 3, 0, 4, 5).reshape(n_ch*flt_h*flt_w, n_bt*out_h*out_w)
    return cols

In [ ]:
# im2colの引数の画像データ
img = np.array([[[[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15],
                [16,17,18,19,20],
                [21,22,23,24,25]     
                ]]])

result = im2col(img,3,3,3,3,1,0)
print(result)

[[ 1.  2.  3.  6.  7.  8. 11. 12. 13.]
 [ 2.  3.  4.  7.  8.  9. 12. 13. 14.]
 [ 3.  4.  5.  8.  9. 10. 13. 14. 15.]
 [ 6.  7.  8. 11. 12. 13. 16. 17. 18.]
 [ 7.  8.  9. 12. 13. 14. 17. 18. 19.]
 [ 8.  9. 10. 13. 14. 15. 18. 19. 20.]
 [11. 12. 13. 16. 17. 18. 21. 22. 23.]
 [12. 13. 14. 17. 18. 19. 22. 23. 24.]
 [13. 14. 15. 18. 19. 20. 23. 24. 25.]]


In [ ]:
# im2colの引数の画像データ
img = np.array([[[[1,3,5,7],
                [2,4,6,8],
                [1,2,3,4],
                [5,6,7,8]
                ]]])

In [ ]:
result = im2col(img,2,2,3,3,1,0)
print(result)

[[1. 3. 5. 2. 4. 6. 1. 2. 3.]
 [3. 5. 7. 4. 6. 8. 2. 3. 4.]
 [2. 4. 6. 1. 2. 3. 5. 6. 7.]
 [4. 6. 8. 2. 3. 4. 6. 7. 8.]]
